### ISSUE TITLE
Rework hint tracking

### ISSUE THREAD

**Issue by robojumper** [robojumper/SS-Randomizer-Tracker#10]
* [x] Consider a text area for hint notes, like the SSHDR tracker 
* [x] Allow tracking multiple hints per hint region
* [ ] Allow tracking hints for not-yet-assigned trials

**Comment by robojumper** [comment]
[HashFrog Tracker](https://hashfrog-tracker.com/) and [Gossip Stones Tracker HD](https://github.com/HapaxL/GSTHD) have been recommended as examples for hint tracking done well.

We could free some UI space by moving the extra locations tracker into the main locations area, as #20 does
