### ISSUE TITLE
Clean up some map tracker parts

### ISSUE THREAD

**Issue by robojumper** [robojumper/SS-Randomizer-Tracker#5]
* [x] The various Marker components have large amounts of code duplication
* [ ] State ownership / display responsibilities are a bit weird; all submap components are active at the same time, but conditionally shown or hidden, and the submaps are also responsible for drawing their markers on the main sky map
* [x] Some map markers are responsible for rendering the area header
