### ISSUE TITLE
Make the tracker more stream-friendly

### ISSUE THREAD

**Issue by robojumper** [robojumper/SS-Randomizer-Tracker#6]
Streamers use the tracker with an OBS capture or an OBS browser source. The existing layout has a few problems:

* [ ] Pippy: Text in the browser source is too small to read (maybe the PWA capability should be advertised a bit more, this should be a good fix?)
* [x] Popup windows sometimes partially overlap the item or map tracker, which is not pretty to look at through the capture. Maybe eliminate popups entirely, or position them more deliberately?
* [ ] Options cannot be viewed or changed without going to the Options screen, which also doesn't look pretty through the capture. Relevant for Random Settings

In general the inventory, the map list, the dungeon tracker and the counters should be considered "Safe Areas" that should not be obstructed, hidden, faded out, ... when using the tracker during a stream.
